name: container

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - id: read_version
      run: echo "VERSION=$(make version)" >> $GITHUB_ENV

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      platforms: linux/amd64,linux/arm64
      context: .
      file: deployment/Dockerfile-router
      push: true
      tags: |
        ghcr.io/rsesek/mailpopbox-router:latest
        ghcr.io/rsesek/mailpopbox-router:${{ env.VERSION }}
